import { Saira  } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";


const saira = Saira ({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${saira.className}  antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}