import { Saira  } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { Playfair_Display } from "next/font/google";


const saira = Saira ({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
  display: 'swap',
  variable: "--font-saira",
})

const playfair = Playfair_Display({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-playfair',
})



export const metadata = {
  title: "Spondon Care Hospital Management Web App",
  description: "Generated by Team CodersArmy",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${saira.variable} ${playfair.variable}  antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}